// <auto-generated />
namespace EmployeeManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class abcV4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abcV4));
        
        string IMigrationMetadata.Id
        {
            get { return "201709191258085_abcV4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
